services:
    padussolarchallenge:
        image: docker.io/library/nginx:latest
        restart: unless-stopped
        networks:
            - website
        volumes:
            - ./website:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        labels:
            - "traefik.enable=true"
            # padussolarchallenge
            - "traefik.http.routers.myapp1.rule=Host(`padussolarchallenge.it`)"
            - "traefik.http.routers.myapp1.entrypoints=websecure"
            - "traefik.http.routers.myapp1.tls.certresolver=le"
            # turbosail
            - "traefik.http.routers.myapp2.rule=Host(`turbosail.it`)"
            - "traefik.http.routers.myapp2.entrypoints=websecure"
            - "traefik.http.routers.myapp2.tls.certresolver=le"
            # catamarano.turbosail.it
            - "traefik.http.routers.myapp3.rule=Host(`catamarano.turbosail.it`)"
            - "traefik.http.routers.myapp3.entrypoints=websecure"
            - "traefik.http.routers.myapp3.tls.certresolver=le"

networks:
  website:
    external: true
