worker_processes auto;

events { worker_connections 1024; }

  http {
    server {

        location / {
          root   /usr/share/nginx/html;
          index  default.html default.htm;

          include  /etc/nginx/mime.types;
    }
  }
}